name: Build
on: [push, pull_request]
jobs:
  alpine:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: jirutka/setup-alpine@v1
      with:
        branch: edge
        packages: build-base git meson eudev-dev glslang-dev hwdata-dev libcap-dev libdisplay-info-dev libinput-dev libliftoff-dev libseat-dev libxcb-dev libxkbcommon-dev mesa-dev pixman-dev vulkan-loader-dev wayland-dev wayland-protocols xcb-util-image-dev xcb-util-renderutil-dev xcb-util-wm-dev xkeyboard-config-dev xwayland-dev
    - run: |
        meson setup build
        meson compile -C build
      shell: alpine.sh {0}

  fedora:
    runs-on: ubuntu-latest
    container: "registry.fedoraproject.org/fedora:rawhide"
    steps:
    - name: Install pre-requisites
      run: |
        dnf --assumeyes install gcc-c++ meson git-core \
                                'pkgconfig(wayland-protocols)' \
                                'pkgconfig(wayland-scanner)' \
                                'pkgconfig(wayland-server)' \
                                'pkgconfig(wlroots)' \
                                'pkgconfig(xcb)' 'pkgconfig(xkbcommon)'
    - uses: actions/checkout@v2
    - name: Build magpie
      run: |
        meson setup build
        meson compile -C build
