name: Build
on: [push]
jobs:
  alpine:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: jirutka/setup-alpine@v1
      with:
        branch: edge
        packages: build-base meson wlroots-dev wayland-dev wayland-protocols libdecor git
    - run: |
        meson setup build
        meson compile -C build
      shell: alpine.sh {0}

  fedora:
    runs-on: ubuntu-latest
    container: "registry.fedoraproject.org/fedora:rawhide"
    steps:
    - name: Install pre-requisites
      run: |
        dnf --assumeyes install gcc-c++ meson git-core \
                                'pkgconfig(wayland-protocols)' \
                                'pkgconfig(wayland-scanner)' \
                                'pkgconfig(wayland-server)' \
                                'pkgconfig(wlroots)' \
                                'pkgconfig(xcb)' 'pkgconfig(xkbcommon)'
    - uses: actions/checkout@v2
    - name: Build magpie
      run: |
        meson setup build
        meson compile -C build
