name: Build
on: [push, pull_request]
jobs:
  alpine:
    runs-on: ubuntu-22.04
    container: "alpine:edge"
    steps:
    - name: Install pre-requisites
      run: |
        apk add build-base git meson hwdata-dev libdisplay-info-dev libinput-dev libliftoff-dev libseat-dev libxcb-dev libxkbcommon-dev pixman-dev wayland-dev wayland-protocols xcb-util-renderutil-dev xcb-util-wm-dev xwayland-dev
    - uses: actions/checkout@v2
    - name: Build magpie
      run: |
        meson setup build
        meson compile -C build

  fedora:
    runs-on: ubuntu-latest
    container: "registry.fedoraproject.org/fedora:rawhide"
    steps:
    - name: Install pre-requisites
      run: |
        dnf --assumeyes install gcc-c++ meson git-core pixman-devel \
          'pkgconfig(hwdata)' \
          'pkgconfig(libdisplay-info)' \
          'pkgconfig(libdrm)' \
          'pkgconfig(libliftoff)' \
          'pkgconfig(libseat)' \
          'pkgconfig(wayland-protocols)' \
          'pkgconfig(wayland-scanner)' \
          'pkgconfig(wayland-server)' \
          'pkgconfig(wlroots)' \
          'pkgconfig(xcb)' \
          'pkgconfig(xcb-ewmh)' \
          'pkgconfig(xcb-renderutil)' \
          'pkgconfig(xkbcommon)' \
          'pkgconfig(xwayland)'
    - uses: actions/checkout@v2
    - name: Build magpie
      run: |
        meson setup build
        meson compile -C build
