name: test
on: [push, pull_request]

jobs:
  test:
    name: flawfinder
    runs-on: ubuntu-latest
    steps:
      - name: Flawfinder Scan
        uses: david-a-wheeler/flawfinder@2.0.19
        with:
          arguments: 'src'
          output: 'flawfinder_results.txt'
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'flawfinder_results.txt'
          path: 'flawfinder_results.txt'
          retention-days: 7
