name: test
on: [push, pull_request]

jobs:
  test:
    name: flawfinder
    runs-on: ubuntu-latest
    steps:
      - name: flawfinder_scan
        uses: david-a-wheeler/flawfinder@2.0.19
        with:
          arguments: '--sarif ./'
          output: 'flawfinder_results.sarif'
